# Generated by Django 4.2.1 on 2023-05-11 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flowers', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='flowers.lot'),
        ),
        migrations.AlterField(
            model_name='review',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
